### get all persons
GET http://localhost:3001/api/persons

### get info
GET http://localhost:3001/info

### get one person
GET http://localhost:3001/api/persons/1

### get one person by id (succeed)
GET http://localhost:3001/api/persons/66c2c59e031c5e49cce66657

### get one person by id (fail)
GET http://localhost:3001/api/persons/66c2c59e031c5e49cce66650

### delete one person
DELETE http://localhost:3001/api/persons/1

### add one new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Lady Gaga G",
  "number": "123456789"
}

### add a person with no name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "123456789"
}

### add a person with no number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Lady Gaga",
  "number": ""
}
